# Stress Detection Model

In [87]:
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt
from sklearn.naive_bayes import BernoulliNB
df=pd.read_csv(r"C:\Users\Administrator\OneDrive\Documents\spam (1) (1).csv",encoding='latin-1')
df.head(n=10)


class                                            message Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   
5  spam  FreeMsg Hey there darling it's been 3 week's n...        NaN   
6   ham  Even my brother is not like to speak with me. ...        NaN   
7   ham  As per your request 'Melle Melle (Oru Minnamin...        NaN   
8  spam  WINNER!! As a valued network customer you have...        NaN   
9  spam  Had your mobile 11 months or more? U R entitle...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN  
5        NaN        NaN  
6        NaN        NaN  
7        NaN        NaN  
8        NaN        NaN  
9        NaN        NaN

In [88]:
 df.describe()

class                 message  \
count   5572                    5572   
unique     2                    5169   
top      ham  Sorry, I'll call later   
freq    4825                      30   

                                               Unnamed: 2  \
count                                                  50   
unique                                                 43   
top      bt not his girlfrnd... G o o d n i g h t . . .@"   
freq                                                    3   

                   Unnamed: 3 Unnamed: 4  
count                      12          6  
unique                     10          5  
top      MK17 92H. 450Ppw 16"    GNT:-)"  
freq                        2          2

In [89]:
df.shape

(5572, 5)

In [90]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   class       5572 non-null   object
 1   message     5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB


In [91]:
df.isnull().sum()

class            0
message          0
Unnamed: 2    5522
Unnamed: 3    5560
Unnamed: 4    5566
dtype: int64

In [92]:
np.unique(df["class"])

array(['ham', 'spam'], dtype=object)

In [93]:
np.unique(df["message"])

array([' &lt;#&gt;  in mca. But not conform.',
       ' &lt;#&gt;  mins but i had to stop somewhere first.',
       ' &lt;DECIMAL&gt; m but its not a common car here so its better to buy from china or asia. Or if i find it less expensive. I.ll holla',
       ..., "yeah, that's what I was thinking",
       'yes baby! I need to stretch open your pussy!',
       'you are sweet as well, princess. Please tell me your likes and dislikes in bed...'],
      dtype=object)

In [94]:
from sklearn.feature_extraction.text import CountVectorizer
x=df["message"].values
y=df["class"].values
cv=CountVectorizer()
x=cv.fit_transform(x)
v=x.toarray()
print(v)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [95]:
first_col=df.pop("message")
df.insert(0,'message',first_col)
df.drop(labels=["Unnamed: 2","Unnamed: 3","Unnamed: 4"],axis=1,inplace=True)
df


message class
0     Go until jurong point, crazy.. Available only ...   ham
1                         Ok lar... Joking wif u oni...   ham
2     Free entry in 2 a wkly comp to win FA Cup fina...  spam
3     U dun say so early hor... U c already then say...   ham
4     Nah I don't think he goes to usf, he lives aro...   ham
...                                                 ...   ...
5567  This is the 2nd time we have tried 2 contact u...  spam
5568              Will ?_ b going to esplanade fr home?   ham
5569  Pity, * was in mood for that. So...any other s...   ham
5570  The guy did some bitching but I acted like i'd...   ham
5571                         Rofl. Its true to its name   ham

[5572 rows x 2 columns]

In [102]:
train_x=x[:4300]
train_y=y[:4300]
test_x=x[4300:]
test_y=y[4300:]


In [103]:
from sklearn.naive_bayes import BernoulliNB
bnb=BernoulliNB(binarize=0.0)
model=bnb.fit(train_x,train_y)
y_pred_train=bnb.predict(train_x)
y_pred_test=bnb.predict(test_x)

In [104]:
print(bnb.score(train_x,train_y)*100)
print(bnb.score(test_x,test_y)*100)

98.76744186046513
98.66352201257862


In [105]:
from sklearn.metrics import classification_report
print(classification_report(train_y,y_pred_train))

              precision    recall  f1-score   support

         ham       0.99      1.00      0.99      3713
        spam       1.00      0.91      0.95       587

    accuracy                           0.99      4300
   macro avg       0.99      0.96      0.97      4300
weighted avg       0.99      0.99      0.99      4300



In [106]:
from sklearn.metrics import classification_report
print(classification_report(test_y,y_pred_test))

              precision    recall  f1-score   support

         ham       0.98      1.00      0.99      1112
        spam       1.00      0.89      0.94       160

    accuracy                           0.99      1272
   macro avg       0.99      0.95      0.97      1272
weighted avg       0.99      0.99      0.99      1272

